### ISSUE TITLE
Casting from cell value to other types

### ISSUE THREAD

**Issue by claudiotomasi** [ashtum/lazycsv#5]
I'm trying to save the values read from a CSV to local variables.
I managed to do that for string variables, but for int/double/etc... it seems kind of tricky. Is there some functionality inside the library that already does it without having to cast the value directly during the reading ?

**Comment by ashtum** [comment]
Parsing cells have a lot of corner cases and customization points which make it difficult to be implemented generically.
You can write a helper function to make it easier, for example :
You can customize convert lambda function for yourself. [Godbolt](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGISQAcpK4AMngMmAByPgBGmMQgAKykAA6oCoRODB7evv5BaRmOAmER0SxxCcl2mA5ZQgRMxAQ5Pn6Btpj2xQwNTQSlUbHxSbaNza15HQrjA%2BFDFSOJAJS2qF7EyOwc5gDM4cjeWADUJrtuyAhNaAwAbmfYJhoAgnsHR5in504zxJisDyerzM%2BwYhy8JzObgQBAIKQUIAA9IjiEwAO4AOmAhAQXhiXiUm1kjAIGLQLERTAUMJ8iIMAC8AJ7IBS3REsKkEeKI94QzB0phMlm3DEIFIpQEvIFclgpAxcqEERkpRisTAYjXHAAqClIxyVKuYbA1GOOAEldfrlaq2McAEqoNGS54zdAgEAELxyzBQnUmh7HG63eIEAD6W1otAUEAdaOOxEdeotJuO4SwqkwCmWQJMAHYrC9jkXjjMmI5kKGqYSCBAMvTMKgqCaIDrll8ACJndslvD1xvNi3LbO7AvPYuBgQzY5MLxEQNdKMd%2BOOskL6NpzAZhQm4ejoHjm5TmdzoMhpcmRJWRKd84Gm2fLUPCDH1DzyPZwvFvOj8fjvBUCcGBmTcUmIY5awIN0QDwBRQwUNVQ3uc4tT1V13V%2BcJgEQvBMCdXZsA/MdfyLb992I38/k9YgGDfWgMVRNEIF3MjiLzTtP2IrolBY39SI48iiy1Y5bjELwfRHHiBMPAhp1nV9fiXCM6IIYg8DYdAmLOH8BOLaTZLnP4FCXNCQCoBMWHDK5iGjX4MXQMsmCY1CVIxVwnOE0TMGYqV%2BIE/9wMM1zkA7LsS0g914k2d1whE2g8HQStiGAHwSUInTyIIBAEzjEyYrEeLEuSthBG/U4zDMPK4oSpoipJcwzFOXMbz3XzyP8iBAtqELdm7EzIuQd1DK8Wgw3WUaqFDVEjC8yT0v1LLHTCqCxtDRtJsMYAfXzMqzBWtaps2%2BrGuanNWuIyiNho2KxK02aSKani2NunyiKLC7qNOS9zAANgvG83BMutMFDUlNTNODMAARyfXKGHTCHIbEsFxLccGlEh/18LSr98zu%2BNMComiTM9b1fW3DVAW209mgxGU5TLT5UBVVEiGITTkIUJ8lM5y80ahv7lhTJ6JP4p7%2BIgqCN1UBGka2UN%2BGIMnMceXGmu814Hpe8IZI5cJNKlXH%2BIZZlWXdFImkJKFAZUzDsNwgNzes%2BJSvqo1MFIJhNtINFMDwYAYVsNA/gvNxeiuRlDFIMxpFzRIMTMUgpESDQU5DhhlEwdBURYKOgm%2BuPkjMAIU9T8rjue15%2BIV8C9JfZc4xAY5HcJbH7u04ja7kz6LDdvVPfd44fb9gOSyDn1r0UgRg2acM1yt8KQAwow7bRPUvG1rhvpBvUqFoVAyzX7XvskEGn2yvUND1Lg9QT45dnVgSTLQWcvjcKEdrdxujqhd%2B3df9%2Bjr9y/mXH%2B5xpybX/mAo6Q9/YEGAQ1UBbhB6%2B1gZApBR0FBj3gWg0eJBPiIKWhFOGtAK7jjFhrdsHBVi0E4IkXgfgOBaFIKgTgb9LDWBLOsTY%2BCQQ8FIHAxhVDVgAGskiXxoRwSQ9DNC8BYRwXgCJL4CK0KsOAsAYCIBQKgWUdB4jkEoOSFIuiEjAC4FwBONARrxARBAGIMjSAxHCE0RknA%2BHkmKgQAA8gwWgLjBGkCwByIw4h/H4D%2BHUYMCJ/GblqLObYTDtZdHsXFGIqJiCMg8FgexNsWCuKoXwAwwAFAADUcJok8YaPJMhBAiDEOwKQ1T5BKDUPY3Q18DBGBQNYaw%2Bg8AxARJAVYTMehRIUV0WoPQXBw0mH4Mw19QjzHKJUCQ0hCiZAEDMkAczUjpHWQwQYSyRgNJqHUAQfQJieDaFs6%2BJyejnLmGUYYCRjmzE2ds0szQDlPJWasBQXCth6BUpgbYPBqG0Okf4uRqgAjfQALTH2OMAZAwUzHx3Amwqwlg9S4EICQMquxr7HA8Do%2BgYE9hcGWLwZRQjSCiOTvoTgUjSC5PpQwphciFEgCUTI1RGiIBIDGikWc%2BiICGOMXoTOuLnmNNqeIBp/BBCKBUOofxQKQW8DRKiFIeSwUcDoaQNlsjOCeNnEKmSjZjjQrhQipFKKuBoogMSoxpL8UUqpTy1YCB/hYASE5CRTKWWX0NcwzgnLuWCKHLSsRDKOC7Ahey0N/CPUxrMPGo18ik0RtWNPDIzhJBAA%3D)
```C++
#include <charconv>
#include <iostream>
#include <lazycsv.hpp>

template<typename... Ts, typename... Is, typename Row>
std::tuple<Ts...> convert_cells(Row row, Is... indexes)
{
    static_assert(sizeof...(Ts) == sizeof...(Is));
    const auto cells = row.cells(indexes...);

    const auto convert = []<typename T>(auto cell)
    {
        if constexpr (std::is_same_v<T, std::string_view>)
        {
            return cell.raw();
        }
        else
        {
            T value;
            const auto str = cell.trimed();
            const auto res = std::from_chars(str.data(), str.end(), value);

            if (res.ec == std::errc::invalid_argument)
                throw std::invalid_argument{ "invalid_argument" };

            if (res.ec == std::errc::result_out_of_range)
                throw std::out_of_range{ "out_of_range" };

            return value;
        }
    };

    return [&]<std::size_t... I_seq>(std::index_sequence<I_seq...>)
    {
        return std::tuple<Ts...>{ convert.template operator()<Ts>(cells[I_seq])... };
    }
    (std::index_sequence_for<Ts...>{});
}

int main()
{
    lazycsv::parser<std::string_view> parser{ "name,age,weight,score\nShayan,24,75.2,145000\nPedram,28,65.5,280000" };

    for (const auto row : parser)
    {
        const auto [name, age, weight, score] = convert_cells<std::string_view, uint16_t, float, uint64_t>(row, 0, 1, 2, 3);
        std::cout << "name: " << name << " age: " << age << " weight: " << weight << " score: " << score << std::endl;
    }
}
```

**Comment by claudiotomasi** [comment]
Ok I'm trying it out right now, but actually the std of the project I'm working on must be 17.
Furthermore I get seg fault 11 if I try out your code. But I get the reasoning behind it, I'll give it a try myself. Thank you
