### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by claudiotomasi** [ashtum/lazycsv#6]
I noticed that, since the parsing is based on mmap functions, the library cannot work on non-unix-based system, e.g., windows. Is it planned a version of lazycsv for windows, maintaning the current speedness of parsing?

Thank you

**Comment by ashtum** [comment]
Hi
The class `mmap_source` only works in unix-systems, i didn't have access to a windows dev env right now for making this class  portable.
I think you can use [mio](https://github.com/mandreyel/mio) to make your own windows compatible `mmap_source`.
