### ISSUE TITLE
parser does not decode appearance of "escaped" quote_char within individual cells

### ISSUE THREAD

**Issue by droolinggeezer** [ashtum/lazycsv#7]
The project allows for quoting of individual cell contents (via quote_char) but does not provide for the recognition of embedded, quote_char  characters within quoted cell value strings. Ideally the project should at least support RFC 4180 encoding or, better, the ability to specify escape character (e.g., quote_escape_char) to be used with literal appearances of quote_char in the quoted cell string. The latter will enable support for both RFC4180 encoding rules (quote_char = " and quote_escape_char = " )and the non-standard, but often used backslash escaping used by various database table exports (quote_char = " and quote_escape_char = \ ).

**Comment by ashtum** [comment]
> The project allows for quoting of individual cell contents (via quote_char) **but does not provide for the recognition of embedded, quote_char characters within quoted cell value strings**.

I couldn't follow the issue. Could you please provide more details? Hasn't this already been addressed in the code? (except for specifying the quote_escape_char) https://github.com/ashtum/lazycsv/blob/844e3f318af2d9ede96039dd9f57ebf4cad59ce2/test/main.cpp#L131
